passwordDefaults:
    minPWLength: 8
    maxPWLength: 64
    asciiOnly: true
    passwordRegEx: '^[ -~]+$'
    excludedPWFilepath: "../prohibitedPasswords/CommonPasswords.txt"


debugging:
    debug: false
    testDebug: true

testing:
    testAtRun: false