passwordDefaults:
    minPWLength: 8
    maxPWLength: 64
    asciiOnly: true
    passwordRegEx: '^[ -~]+$'
    excludedPWFilepath: "./prohibitedPasswords/CommonPasswords.txt"


debugging:
    debug: true
    testDebug: true

testing:
    testAtRun: false